### ISSUE TITLE
Is this intended behavior?

### ISSUE THREAD

**Issue by doomsower** [gpfunk/redux-timeout#3]
It seems to me that this middleware is doing something different from those two use cases in documentation.
The timeout triggers not after every occurrence of watched action, but after every two occurrences.
1. ADD_TIMEOUT
2. Timeout fires, monitor.dispatching set to true
3. ACTION_TO_WATCH is dispatched for the first time, but monitor.dispatching is currently true, so it is set to false and nothing else happens
4. ACTION_TO_WATCH is dispatched for the second time, now monitor.dispatching is false and timeout is set
5. Timeout fires, and we are at 2) again

Please correct me If I understand it wrong.

**Comment by gpfunk** [comment]
Nope, definitely not intended, sorry about that.  I discovered this a couple days ago as well, I should have a fix up tonight.

**Comment by gpfunk** [comment]
Fixed with this commit https://github.com/gpfunk/redux-timeout/commit/a9a4bf52998adf4d2556777085a8f276658a0ca7
I had added this in for a specific use case I had without realizing it had broken most other use cases
